// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDopMKlnioLyOzENLpmof9Fr01iHUQnZ5g',
    appId: '1:1073977275866:web:6e276646de823e0b87bce3',
    messagingSenderId: '1073977275866',
    projectId: 'ddnangcao-project',
    authDomain: 'ddnangcao-project.firebaseapp.com',
    storageBucket: 'ddnangcao-project.appspot.com',
    measurementId: 'G-TM9B5KT90L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIjYuc79Euk15fhu6rZ0evlG7RNphdoJM',
    appId: '1:1073977275866:android:e36bfde65e7f5bac87bce3',
    messagingSenderId: '1073977275866',
    projectId: 'ddnangcao-project',
    storageBucket: 'ddnangcao-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8S3kHm9VDKgBC7DfDHVJh1t4_Qi2Uvo',
    appId: '1:1073977275866:ios:bec2b3c9f8eaa75387bce3',
    messagingSenderId: '1073977275866',
    projectId: 'ddnangcao-project',
    storageBucket: 'ddnangcao-project.appspot.com',
    iosBundleId: 'com.example.ddnangcaoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH8S3kHm9VDKgBC7DfDHVJh1t4_Qi2Uvo',
    appId: '1:1073977275866:ios:779c3357c285949087bce3',
    messagingSenderId: '1073977275866',
    projectId: 'ddnangcao-project',
    storageBucket: 'ddnangcao-project.appspot.com',
    iosBundleId: 'com.example.ddnangcaoProject.RunnerTests',
  );
}
